import "~/styles/globals.css";

export const metadata = {
  title: "Applications",
  description: "Generated by create next app",
};

import { SearchService } from "~/search";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <title>parasocial</title>
      </head>
      <body className="bg-slate-800 text-zinc-100">{children}</body>
    </html>
  );
}
