// import "~/styles/globals.css";
import "./global.css";

export const metadata = {
  title: "Applications",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <title>parasocial</title>
      </head>
      <body className="bg-pink-900 text-zinc-100">{children}</body>
    </html>
  );
}
