import "~/styles/globals.css";

export const metadata = {
  title: "Applications",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800 text-zinc-100">{children}</body>
    </html>
  );
}
